-- Fills the Experience and Projects tables with the site's current content.
-- Generated from src/content/content.fallback.ts. Run once, after schema.sql,
-- in the Supabase SQL Editor. It only inserts into EMPTY tables, so running it
-- again never duplicates or overwrites anything you've edited in /admin.

do $seed$
begin
  if not exists (select 1 from public.experiences) then
    insert into public.experiences (sort_order, published, org, href, tags, role_en, role_id, period_en, period_id, context_en, context_id, points_en, points_id) values
      (1, true, $v$SweetieBatter$v$, $v$https://sweetiebatter.vercel.app$v$, array[$v$React.js$v$, $v$CSS$v$, $v$Responsive$v$]::text[], $v$Freelance Frontend Developer$v$, $v$Freelance Frontend Developer$v$, $v$May 2026$v$, $v$Mei 2026$v$, $v$Product catalog website for a pastry brand$v$, $v$Website katalog produk untuk brand pastry$v$, array[$v$Built a responsive product catalog in React.js, so the brand's pastries are easy to browse on any screen.$v$, $v$Reviewed the brand's existing assets with the owner, then reworked the site's visual direction to match them.$v$]::text[], array[$v$Membangun katalog produk yang responsif dengan React.js, sehingga pastry dari brand ini mudah dijelajahi di layar apa pun.$v$, $v$Meninjau aset brand yang sudah ada bersama pemilik, lalu merombak arah visual situs agar selaras dengannya.$v$]::text[]),
      (2, true, $v$Mataram3D$v$, null, array[$v$NestJS$v$, $v$Prisma$v$, $v$JWT$v$, $v$Docker$v$, $v$Railway$v$]::text[], $v$Freelance Backend Developer$v$, $v$Freelance Backend Developer$v$, $v$Sep 2026$v$, $v$Sep 2026$v$, $v$Admin dashboard backend for a client$v$, $v$Backend dashboard admin untuk klien$v$, array[$v$Designed and built a NestJS admin backend from scratch for an existing client frontend, with JWT authentication and role-based access control.$v$, $v$Modelled the database with Prisma on Supabase, handled image upload and storage, containerised the service with Docker, and deployed it to Railway.$v$]::text[], array[$v$Merancang dan membangun backend admin NestJS dari nol untuk frontend klien yang sudah ada, lengkap dengan autentikasi JWT dan role-based access control.$v$, $v$Memodelkan database dengan Prisma di Supabase, menangani unggah dan penyimpanan gambar, membungkus layanan dengan Docker, lalu men-deploy-nya ke Railway.$v$]::text[]),
      (3, true, $v$Trading notification bot$v$, null, array[$v$MQL4$v$, $v$Telegram API$v$]::text[], $v$Freelance Automation Developer$v$, $v$Freelance Automation Developer$v$, $v$Sep 2026 – Present$v$, $v$Sep 2026 – Sekarang$v$, $v$MetaTrader 4 client project$v$, $v$Proyek klien MetaTrader 4$v$, array[$v$Built an MQL4 bot around a five-stage state machine that tracks market conditions across several timeframes at once.$v$, $v$Integrated the Telegram API to send the client real-time alerts the moment a setup condition is met.$v$]::text[], array[$v$Membangun bot MQL4 berbasis state machine lima tahap yang memantau kondisi pasar di beberapa timeframe sekaligus.$v$, $v$Mengintegrasikan Telegram API untuk mengirim notifikasi real-time ke klien begitu kondisi setup terpenuhi.$v$]::text[]);
  end if;

  if not exists (select 1 from public.projects) then
    insert into public.projects (sort_order, published, name, href, stack, role_en, role_id, status_en, status_id, summary_en, summary_id, problem_en, problem_id, solution_en, solution_id, contribution_en, contribution_id, lessons_en, lessons_id) values
      (1, true, $v$Tryvel$v$, $v$https://tryvel-code.vercel.app/pages/home.html$v$, array[$v$HTML$v$, $v$CSS$v$, $v$JavaScript$v$]::text[], $v$Frontend Developer$v$, $v$Frontend Developer$v$, $v$Frontend$v$, $v$Frontend$v$, $v$A travel recommendation app that helps users discover destinations in a city they plan to visit or are already in.$v$, $v$Aplikasi rekomendasi wisata yang membantu pengguna menemukan destinasi di kota yang akan atau sedang mereka kunjungi.$v$, $v$Travelers often struggle to find relevant destination recommendations in a new city, with information scattered across many sources.$v$, $v$Wisatawan sering kesulitan menemukan rekomendasi destinasi yang relevan di kota baru, karena informasinya tersebar di banyak sumber.$v$, $v$Defined the core problem, drafted a PRD to scope the product, and built a clean frontend that surfaces recommendations based on the user's chosen city.$v$, $v$Merumuskan masalah inti, menyusun PRD untuk membatasi cakupan produk, dan membangun frontend rapi yang menampilkan rekomendasi sesuai kota pilihan pengguna.$v$, $v$Problem definition, product ideation, the PRD, and frontend implementation with my team.$v$, $v$Perumusan masalah, ideasi produk, penyusunan PRD, dan implementasi frontend bersama tim.$v$, $v$How to turn a raw problem into a structured product idea, and the fundamentals of building with HTML, CSS, and JavaScript.$v$, $v$Cara mengubah masalah mentah menjadi ide produk yang terstruktur, serta dasar-dasar membangun dengan HTML, CSS, dan JavaScript.$v$),
      (2, true, $v$StairsLife$v$, $v$https://www.stairslife.com$v$, array[$v$NestJS$v$, $v$Supabase$v$, $v$Xendit$v$, $v$Next.js$v$, $v$Railway$v$]::text[], $v$Full-stack Developer$v$, $v$Full-stack Developer$v$, $v$Live product$v$, $v$Produk live$v$, $v$A two-sided freelance marketplace connecting students with small businesses — built end to end and live today.$v$, $v$Marketplace freelance dua sisi yang mempertemukan mahasiswa dengan usaha kecil — dibangun end-to-end dan kini sudah live.$v$, $v$Students need income and real-world experience outside lectures, while small businesses need affordable help to keep costs down.$v$, $v$Mahasiswa butuh penghasilan dan pengalaman nyata di luar kuliah, sementara usaha kecil butuh bantuan terjangkau untuk menekan biaya.$v$, $v$Built the whole product: a NestJS API on Supabase, Xendit escrow payments that release funds only when a job is done, and private file storage with time-limited links.$v$, $v$Membangun produk secara utuh: API NestJS di atas Supabase, pembayaran escrow Xendit yang baru cair setelah pekerjaan selesai, dan penyimpanan file privat dengan link berbatas waktu.$v$, $v$End-to-end development — API, database, payments, deployment on Railway and Vercel, plus a Flutter app on the same API.$v$, $v$Pengembangan end-to-end — API, database, pembayaran, deployment di Railway dan Vercel, serta aplikasi Flutter dengan API yang sama.$v$, $v$How to handle money and sensitive files responsibly, and how one well-designed API can serve both web and mobile.$v$, $v$Cara menangani uang dan file sensitif secara bertanggung jawab, dan bagaimana satu API yang dirancang baik bisa melayani web sekaligus mobile.$v$),
      (3, true, $v$Sales Forecast App$v$, $v$https://model-prediksi-penjualan-prophet-jjm4c5tege7q79za6nfyqv.streamlit.app/$v$, array[$v$Python$v$, $v$Streamlit$v$, $v$Prophet$v$]::text[], $v$Developer$v$, $v$Developer$v$, $v$Data app$v$, $v$Aplikasi data$v$, $v$A no-code forecasting tool that lets business owners predict demand, simulate growth scenarios, and get low-stock alerts.$v$, $v$Alat peramalan tanpa kode yang membantu pemilik usaha memprediksi permintaan, menyimulasikan skenario pertumbuhan, dan mendapat peringatan stok menipis.$v$, $v$Small businesses struggle to forecast sales. Without clear projections, stock decisions become guesswork — overstocking ties up capital, understocking loses sales.$v$, $v$Usaha kecil kesulitan meramal penjualan. Tanpa proyeksi yang jelas, keputusan stok jadi tebak-tebakan — stok berlebih menahan modal, stok kurang membuat penjualan hilang.$v$, $v$Built a Streamlit app around a Prophet time-series model. Users upload CSV sales data, pick a product, tune parameters, and get forecasts with actionable insights.$v$, $v$Membangun aplikasi Streamlit di sekitar model time-series Prophet. Pengguna mengunggah data penjualan CSV, memilih produk, mengatur parameter, lalu langsung mendapat ramalan beserta insight yang bisa ditindaklanjuti.$v$, $v$Architecture, the data pipeline and input validation, Prophet integration with scenario simulation, code review, and deployment.$v$, $v$Arsitektur, pipeline data dan validasi input, integrasi Prophet dengan simulasi skenario, code review, dan deployment.$v$, $v$How to turn a working model into a complete app that translates data into real business decisions.$v$, $v$Cara mengubah model yang berjalan menjadi aplikasi utuh yang menerjemahkan data menjadi keputusan bisnis nyata.$v$),
      (4, true, $v$Portfolio Website$v$, $v$https://www.austinyang.tech$v$, array[$v$Next.js$v$, $v$NestJS$v$, $v$Supabase$v$, $v$Gemini API$v$]::text[], $v$Full-stack Developer$v$, $v$Full-stack Developer$v$, $v$Full stack$v$, $v$Full stack$v$, $v$This site — a bilingual portfolio with dark mode, a live contact form, an admin panel, and an AI assistant grounded in my own data.$v$, $v$Situs ini — portfolio dua bahasa dengan mode gelap, form kontak yang berfungsi, panel admin, dan asisten AI yang hanya menjawab dari data saya.$v$, $v$I needed an online presence that goes beyond a static page, with real backend features instead of a mockup.$v$, $v$Saya butuh kehadiran online yang lebih dari sekadar halaman statis, dengan fitur backend sungguhan, bukan sekadar mockup.$v$, $v$A Next.js frontend backed by a separate NestJS API on Supabase: a contact form with email alerts, an admin panel to manage this content, privacy-friendly visitor stats, and a Gemini-powered assistant that only answers from a curated knowledge base.$v$, $v$Frontend Next.js yang didukung API NestJS terpisah di atas Supabase: form kontak dengan notifikasi email, panel admin untuk mengelola konten ini, statistik pengunjung yang menjaga privasi, serta asisten bertenaga Gemini yang hanya menjawab dari knowledge base terkurasi.$v$, $v$Design implementation, frontend and motion, the NestJS API with a secured admin panel, the assistant, and the English/Indonesian localisation.$v$, $v$Implementasi desain, frontend dan animasi, API NestJS dengan panel admin yang aman, asisten AI, serta lokalisasi Inggris/Indonesia.$v$, $v$How to split a product into a frontend and an API cleanly, how to secure an admin panel end to end, and how much restraint good motion design takes.$v$, $v$Cara memisahkan produk menjadi frontend dan API dengan rapi, cara mengamankan panel admin dari ujung ke ujung, dan betapa pentingnya menahan diri dalam desain animasi.$v$);
  end if;
end
$seed$;
