import type { ContentRows } from "./content.types";

/**
 * Built-in copy of the Experience and Projects content. The API serves this
 * whenever Supabase is unreachable (e.g. a paused free-tier project), and
 * supabase/seed-content.sql was generated from it to fill the tables the
 * first time. Once the tables exist, edit content in /admin, not here.
 */
export const FALLBACK_CONTENT: ContentRows = {
  experiences: [
    {
      id: "fallback-xp-1",
      sort_order: 1,
      published: true,
      org: "SweetieBatter",
      href: "https://sweetiebatter.vercel.app",
      tags: ["React.js", "CSS", "Responsive"],
      role_en: "Freelance Frontend Developer",
      role_id: "Freelance Frontend Developer",
      period_en: "May 2026",
      period_id: "Mei 2026",
      context_en: "Product catalog website for a pastry brand",
      context_id: "Website katalog produk untuk brand pastry",
      points_en: [
        "Built a responsive product catalog in React.js, so the brand's pastries are easy to browse on any screen.",
        "Reviewed the brand's existing assets with the owner, then reworked the site's visual direction to match them.",
      ],
      points_id: [
        "Membangun katalog produk yang responsif dengan React.js, sehingga pastry dari brand ini mudah dijelajahi di layar apa pun.",
        "Meninjau aset brand yang sudah ada bersama pemilik, lalu merombak arah visual situs agar selaras dengannya.",
      ],
    },
    {
      id: "fallback-xp-2",
      sort_order: 2,
      published: true,
      org: "Mataram3D",
      href: null,
      tags: ["NestJS", "Prisma", "JWT", "Docker", "Railway"],
      role_en: "Freelance Backend Developer",
      role_id: "Freelance Backend Developer",
      period_en: "Sep 2026",
      period_id: "Sep 2026",
      context_en: "Admin dashboard backend for a client",
      context_id: "Backend dashboard admin untuk klien",
      points_en: [
        "Designed and built a NestJS admin backend from scratch for an existing client frontend, with JWT authentication and role-based access control.",
        "Modelled the database with Prisma on Supabase, handled image upload and storage, containerised the service with Docker, and deployed it to Railway.",
      ],
      points_id: [
        "Merancang dan membangun backend admin NestJS dari nol untuk frontend klien yang sudah ada, lengkap dengan autentikasi JWT dan role-based access control.",
        "Memodelkan database dengan Prisma di Supabase, menangani unggah dan penyimpanan gambar, membungkus layanan dengan Docker, lalu men-deploy-nya ke Railway.",
      ],
    },
    {
      id: "fallback-xp-3",
      sort_order: 3,
      published: true,
      org: "Trading notification bot",
      href: null,
      tags: ["MQL4", "Telegram API"],
      role_en: "Freelance Automation Developer",
      role_id: "Freelance Automation Developer",
      period_en: "Sep 2026 – Present",
      period_id: "Sep 2026 – Sekarang",
      context_en: "MetaTrader 4 client project",
      context_id: "Proyek klien MetaTrader 4",
      points_en: [
        "Built an MQL4 bot around a five-stage state machine that tracks market conditions across several timeframes at once.",
        "Integrated the Telegram API to send the client real-time alerts the moment a setup condition is met.",
      ],
      points_id: [
        "Membangun bot MQL4 berbasis state machine lima tahap yang memantau kondisi pasar di beberapa timeframe sekaligus.",
        "Mengintegrasikan Telegram API untuk mengirim notifikasi real-time ke klien begitu kondisi setup terpenuhi.",
      ],
    },
  ],
  projects: [
    {
      id: "fallback-pr-1",
      sort_order: 1,
      published: true,
      name: "Tryvel",
      href: "https://tryvel-code.vercel.app/pages/home.html",
      stack: ["HTML", "CSS", "JavaScript"],
      role_en: "Frontend Developer",
      role_id: "Frontend Developer",
      status_en: "Frontend",
      status_id: "Frontend",
      summary_en: "A travel recommendation app that helps users discover destinations in a city they plan to visit or are already in.",
      summary_id: "Aplikasi rekomendasi wisata yang membantu pengguna menemukan destinasi di kota yang akan atau sedang mereka kunjungi.",
      problem_en: "Travelers often struggle to find relevant destination recommendations in a new city, with information scattered across many sources.",
      problem_id: "Wisatawan sering kesulitan menemukan rekomendasi destinasi yang relevan di kota baru, karena informasinya tersebar di banyak sumber.",
      solution_en: "Defined the core problem, drafted a PRD to scope the product, and built a clean frontend that surfaces recommendations based on the user's chosen city.",
      solution_id: "Merumuskan masalah inti, menyusun PRD untuk membatasi cakupan produk, dan membangun frontend rapi yang menampilkan rekomendasi sesuai kota pilihan pengguna.",
      contribution_en: "Problem definition, product ideation, the PRD, and frontend implementation with my team.",
      contribution_id: "Perumusan masalah, ideasi produk, penyusunan PRD, dan implementasi frontend bersama tim.",
      lessons_en: "How to turn a raw problem into a structured product idea, and the fundamentals of building with HTML, CSS, and JavaScript.",
      lessons_id: "Cara mengubah masalah mentah menjadi ide produk yang terstruktur, serta dasar-dasar membangun dengan HTML, CSS, dan JavaScript.",
    },
    {
      id: "fallback-pr-2",
      sort_order: 2,
      published: true,
      name: "StairsLife",
      href: "https://www.stairslife.com",
      stack: ["NestJS", "Supabase", "Xendit", "Next.js", "Railway"],
      role_en: "Full-stack Developer",
      role_id: "Full-stack Developer",
      status_en: "Live product",
      status_id: "Produk live",
      summary_en: "A two-sided freelance marketplace connecting students with small businesses — built end to end and live today.",
      summary_id: "Marketplace freelance dua sisi yang mempertemukan mahasiswa dengan usaha kecil — dibangun end-to-end dan kini sudah live.",
      problem_en: "Students need income and real-world experience outside lectures, while small businesses need affordable help to keep costs down.",
      problem_id: "Mahasiswa butuh penghasilan dan pengalaman nyata di luar kuliah, sementara usaha kecil butuh bantuan terjangkau untuk menekan biaya.",
      solution_en: "Built the whole product: a NestJS API on Supabase, Xendit escrow payments that release funds only when a job is done, and private file storage with time-limited links.",
      solution_id: "Membangun produk secara utuh: API NestJS di atas Supabase, pembayaran escrow Xendit yang baru cair setelah pekerjaan selesai, dan penyimpanan file privat dengan link berbatas waktu.",
      contribution_en: "End-to-end development — API, database, payments, deployment on Railway and Vercel, plus a Flutter app on the same API.",
      contribution_id: "Pengembangan end-to-end — API, database, pembayaran, deployment di Railway dan Vercel, serta aplikasi Flutter dengan API yang sama.",
      lessons_en: "How to handle money and sensitive files responsibly, and how one well-designed API can serve both web and mobile.",
      lessons_id: "Cara menangani uang dan file sensitif secara bertanggung jawab, dan bagaimana satu API yang dirancang baik bisa melayani web sekaligus mobile.",
    },
    {
      id: "fallback-pr-3",
      sort_order: 3,
      published: true,
      name: "Sales Forecast App",
      href: "https://model-prediksi-penjualan-prophet-jjm4c5tege7q79za6nfyqv.streamlit.app/",
      stack: ["Python", "Streamlit", "Prophet"],
      role_en: "Developer",
      role_id: "Developer",
      status_en: "Data app",
      status_id: "Aplikasi data",
      summary_en: "A no-code forecasting tool that lets business owners predict demand, simulate growth scenarios, and get low-stock alerts.",
      summary_id: "Alat peramalan tanpa kode yang membantu pemilik usaha memprediksi permintaan, menyimulasikan skenario pertumbuhan, dan mendapat peringatan stok menipis.",
      problem_en: "Small businesses struggle to forecast sales. Without clear projections, stock decisions become guesswork — overstocking ties up capital, understocking loses sales.",
      problem_id: "Usaha kecil kesulitan meramal penjualan. Tanpa proyeksi yang jelas, keputusan stok jadi tebak-tebakan — stok berlebih menahan modal, stok kurang membuat penjualan hilang.",
      solution_en: "Built a Streamlit app around a Prophet time-series model. Users upload CSV sales data, pick a product, tune parameters, and get forecasts with actionable insights.",
      solution_id: "Membangun aplikasi Streamlit di sekitar model time-series Prophet. Pengguna mengunggah data penjualan CSV, memilih produk, mengatur parameter, lalu langsung mendapat ramalan beserta insight yang bisa ditindaklanjuti.",
      contribution_en: "Architecture, the data pipeline and input validation, Prophet integration with scenario simulation, code review, and deployment.",
      contribution_id: "Arsitektur, pipeline data dan validasi input, integrasi Prophet dengan simulasi skenario, code review, dan deployment.",
      lessons_en: "How to turn a working model into a complete app that translates data into real business decisions.",
      lessons_id: "Cara mengubah model yang berjalan menjadi aplikasi utuh yang menerjemahkan data menjadi keputusan bisnis nyata.",
    },
    {
      id: "fallback-pr-4",
      sort_order: 4,
      published: true,
      name: "Portfolio Website",
      href: "https://www.austinyang.tech",
      stack: ["Next.js", "NestJS", "Supabase", "Gemini API"],
      role_en: "Full-stack Developer",
      role_id: "Full-stack Developer",
      status_en: "Full stack",
      status_id: "Full stack",
      summary_en: "This site — a bilingual portfolio with dark mode, a live contact form, an admin panel, and an AI assistant grounded in my own data.",
      summary_id: "Situs ini — portfolio dua bahasa dengan mode gelap, form kontak yang berfungsi, panel admin, dan asisten AI yang hanya menjawab dari data saya.",
      problem_en: "I needed an online presence that goes beyond a static page, with real backend features instead of a mockup.",
      problem_id: "Saya butuh kehadiran online yang lebih dari sekadar halaman statis, dengan fitur backend sungguhan, bukan sekadar mockup.",
      solution_en: "A Next.js frontend backed by a separate NestJS API on Supabase: a contact form with email alerts, an admin panel to manage this content, privacy-friendly visitor stats, and a Gemini-powered assistant that only answers from a curated knowledge base.",
      solution_id: "Frontend Next.js yang didukung API NestJS terpisah di atas Supabase: form kontak dengan notifikasi email, panel admin untuk mengelola konten ini, statistik pengunjung yang menjaga privasi, serta asisten bertenaga Gemini yang hanya menjawab dari knowledge base terkurasi.",
      contribution_en: "Design implementation, frontend and motion, the NestJS API with a secured admin panel, the assistant, and the English/Indonesian localisation.",
      contribution_id: "Implementasi desain, frontend dan animasi, API NestJS dengan panel admin yang aman, asisten AI, serta lokalisasi Inggris/Indonesia.",
      lessons_en: "How to split a product into a frontend and an API cleanly, how to secure an admin panel end to end, and how much restraint good motion design takes.",
      lessons_id: "Cara memisahkan produk menjadi frontend dan API dengan rapi, cara mengamankan panel admin dari ujung ke ujung, dan betapa pentingnya menahan diri dalam desain animasi.",
    },
  ],
};
